[machine]
ram_length = "64Mi"
entrypoint = "/mnt/app/app /dev/pmem2 1 && /mnt/app/app /dev/pmem2"
use_docker_env = false # cartesi cli option to avoid using docker rootfs envs

[drives.root]
builder = "docker"
dockerfile = "Dockerfile"
target = "base"
format = "ext2"
avoid_overwrite = "true"
extra_size = "2Mb"
buildx = true

[drives.app]
builder = "docker"
dockerfile = "Dockerfile"
target = "app"
format = "sqfs"
buildx = true

[drives.state]
builder = "raw"
length = "32Mb"
user = "dapp"
mount = "false"
